routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\Auth\ResetPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});
//Route login-logout
Route::prefix('homes')->group(function () {
    Route::get('/login', [LoginController::class, 'showFormLogin'])->name('login');
    Route::post('/login', [LoginController::class, 'login'])->name('homes.login');
    Route::get('/logout', [LoginController::class, 'logout'])->name('homes.logout');
});
//Route middleware-auth
Route::middleware('auth')->group(function () {
    //Route change-password
    Route::get('/change-password', [LoginController::class, 'showFormChangePassword'])->name('homes.showFormChangePassword');
    Route::post('/change-password', [LoginController::class, 'changePassword'])->name('homes.changePassword');
    //Route profile-view
    Route::get('/profile', [UserController::class, 'showProfile'])->name('profile');
    //Route list-user
    Route::get('/users/list', [UserController::class, 'index'])->name('users.index')->middleware('check-permission:' . config('const.ROLE.MANAGER'));
    //Route check first-login && check-role
    Route::middleware('check-permission')->group(function () {
        //Route departments
        Route::resource('departments', 'DepartmentController')->except(['edit', 'update', 'destroy']);
        Route::get('{id}/edit', [DepartmentController::class, 'edit'])->name('departments.edit');
        Route::post('{id}/update', [DepartmentController::class, 'update'])->name('departments.update');
        Route::get('{id}/delete', [DepartmentController::class, 'destroy'])->name('departments.destroy');
        //Route classes
        Route::resource('classes', 'ClassesController')->except(['edit', 'update', 'destroy']);
        Route::get('{id}/edit', [ClassesController::class, 'edit'])->name('classes.edit');
        Route::post('{id}/update', [ClassesController::class, 'update'])->name('classes.update');
        Route::get('{id}/delete', [ClassesController::class, 'destroy'])->name('classes.destroy');
        //Route Schedule
        Route::resource('schedule', 'ScheduleController')->except(['edit', 'destroy']);
        Route::get('{id}/edit', [ScheduleController::class, 'edit'])->name('schedules.edit');
        Route::get('{id}/delete', [ScheduleController::class, 'destroy'])->name('schedules.destroy');

        //Route users
        Route::resource('users', 'UserController')->except(['index']);
        //Route profile
        Route::prefix('profiles')->group(function () {
            Route::get('/{id}/update-profile', [UserController::class, 'showFormUpdateProfile'])->name('profiles.showFormUpdateProfile');
            Route::post('/{id}/update-profile', [UserController::class, 'updateProfile'])->name('profiles.updateProfile');
        });
        //Route reset-password
        Route::post('/reset-password', [ResetPasswordController::class, 'resetPassword'])->name('reset-password');
        //Export data
        Route::get('/export', [UserController::class, 'export'])->name('export');
    });
    });

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Department extends Model
{
    use HasFactory;
    protected $table = 'departments';
    public $fillable = [ 'name', 'status', 'manager'];

    public function user() 
    {
        return $this->hasMany(User::class, "department_id", "id");
    }

}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Maatwebsite\Excel\Excel;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\DepartmentRequest;
use App\Repositories\User\UserRepositoryInterface;
use App\Repositories\Department\DepartmentRepositoryInterface;

class DepartmentController extends Controller
{
    function __construct(DepartmentRepositoryInterface $department, UserRepositoryInterface $users)
    {
        $this->department = $department;
    }

    public function index()
    {
        $departments = $this->department->getAllDepartments();
        return view('departments.list', compact("departments"));
    }

    public function create()
    {
        return view('departments.create');
    }

    public function store(DepartmentRequest $request)
    {
        $data = $request->except('_token');
        $this->department->store($data);
        return redirect()->route('departments.index')->with('success', 'Tạo khoa thành công!');
    }

    public function edit($id)
    {
        $departments = $this->department->getById($id);
        return view('departments.update', compact('departments'));
    }

    public function update(DepartmentRequest $request, $id)
    {
        $data = $request->except("_token");
        $this->department->update($data, $id);
        return redirect()->route('departments.index')->with('success', 'Sửa khoa thành công!');
    }

    public function destroy($id)
    {
        $this->department->destroy($id);
        return redirect()->route('departments.index')->with('success', 'Xoá khoa thành công!');
    }
}

resources/views/departments/create.blade.php
@extends('layouts.master')
@section('title')
    Thêm
@endsection
@section('content')
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Thêm khoa</h4>
                <form action="{{ route('departments.store') }}" class="forms-sample" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="exampleInputDepartmentname">Name <span class="text-danger">*</span></label>
                        <input type="text" name="name" class="form-control" >
                        @error('name')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputStatus">Trạng thái</label>
                        {{-- <input type="text" name="status" class="form-control" > --}}
                        <select class="form-control2" name="status">
                            <option value="Đang hoạt động">Đang hoạt động</option>
                            <option value="Tạm ngưng">Tạm ngưng</option>
                                    </select>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button type="button" onclick="window.location.href='{{ route('departments.index') }}'"
                        class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/departments/list.blade.php
@extends('layouts.master')
@section('title')
    Danh sách khoa
@endsection
@section('content')
    <div class="col-lg-12 grid-margin stretch-card background-color-grey">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Danh sách khoa</h4>
                <p class="card-description">
                </p>
                @if (session()->has('success'))
                    <h3 class="alert alert-success">
                        {{ session()->get('success') }}
                    </h3>
                @endif
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Tên khoa</th>
                            <th>Trạng thái</th>
                            <th>Trưởng khoa</th>
                            <th>Create at</th>
                            <th>Update at</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (count($departments))
                            @foreach ($departments as $key => $department)
                                <tr>
                                    <td class="py-1">
                                        {{ $key + 1 }}
                                    </td>
                                    <td>
                                        {{ $department->name }}
                                    </td>
                                    <td>
                                        {{ $department->status }}
                                    </td>
                                    <td>
                                        <!-- @foreach ($department->user as $manager)
                                            {{ $manager->name . '. ' }}
                                        @endforeach -->
                                    </td>
                                    <td>
                                        {{ $department->created_at->format("d/m/Y") }}
                                    </td>
                                    <td>
                                        {{ $department->updated_at->format("d/m/Y") }}
                                    </td>
                                    <td>
                                        <a href="{{ route('departments.edit', $department->id) }}"
                                            class="btn btn-primary mr-2">
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        </a>
                                        <a class="btn btn-danger" href="#" data-toggle="modal"
                                            data-target="#ModalDelete{{ $department->id }}">
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                        </a>
                                        <form id="delete_form_{{ $department->id }}" method="get"
                                            action="{{ route('departments.destroy', $department->id) }}"
                                            style="display:none">
                                            @csrf
                                        </form>
                                    </td>
                                    @include('modals.delete-department')
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td class="text-center" colspan="12">Không tìm thấy trang</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
                {{ $departments->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/departments/update.blade.php
@extends('layouts.master')
@section('title')
    Danh sách khoa
@endsection
@section('content')
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Cập nhập</h4>
                <form action="{{ route('departments.update', $departments->id) }}" class="forms-sample" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="exampleInputDepartmentname">Tên khoa <span class="text-danger">*</span></label>
                        <input type="text" name="name" class="form-control" value="{{ $departments->name }}">
                        @error('name')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputDescription">Trạng thái hoạt động</label>
                        <select class="form-control" name="status" placeholder="{{ $departments->status}}">
                                        <option value="Đang hoạt động">Đang hoạt động</option>
                                        <option value="Tạm ngưng">Tạm ngưng</option>
                                    </select>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button type="button" onclick="window.location.href='{{ route('departments.index') }}'"
                        class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
@endsection