routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\Auth\ResetPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});
//Route login-logout
Route::prefix('homes')->group(function () {
    Route::get('/login', [LoginController::class, 'showFormLogin'])->name('login');
    Route::post('/login', [LoginController::class, 'login'])->name('homes.login');
    Route::get('/logout', [LoginController::class, 'logout'])->name('homes.logout');
});
//Route middleware-auth
Route::middleware('auth')->group(function () {
    //Route change-password
    Route::get('/change-password', [LoginController::class, 'showFormChangePassword'])->name('homes.showFormChangePassword');
    Route::post('/change-password', [LoginController::class, 'changePassword'])->name('homes.changePassword');
    //Route profile-view
    Route::get('/profile', [UserController::class, 'showProfile'])->name('profile');
    //Route list-user
    Route::get('/users/list', [UserController::class, 'index'])->name('users.index')->middleware('check-permission:' . config('const.ROLE.MANAGER'));
    //Route check first-login && check-role
    Route::middleware('check-permission')->group(function () {
        //Route departments
        Route::resource('departments', 'DepartmentController')->except(['edit', 'update', 'destroy']);
        Route::get('{id}/edit', [DepartmentController::class, 'edit'])->name('departments.edit');
        Route::post('{id}/update', [DepartmentController::class, 'update'])->name('departments.update');
        Route::get('{id}/delete', [DepartmentController::class, 'destroy'])->name('departments.destroy');
        //Route classes
        Route::resource('classes', 'ClassesController')->except(['edit', 'update', 'destroy']);
        Route::get('{id}/edit', [ClassesController::class, 'edit'])->name('classes.edit');
        Route::post('{id}/update', [ClassesController::class, 'update'])->name('classes.update');
        Route::get('{id}/delete', [ClassesController::class, 'destroy'])->name('classes.destroy');
        //Route Schedule
        Route::resource('schedule', 'ScheduleController')->except(['edit', 'destroy']);
        Route::get('{id}/edit', [ScheduleController::class, 'edit'])->name('schedules.edit');
        Route::get('{id}/delete', [ScheduleController::class, 'destroy'])->name('schedules.destroy');

        //Route users
        Route::resource('users', 'UserController')->except(['index']);
        //Route profile
        Route::prefix('profiles')->group(function () {
            Route::get('/{id}/update-profile', [UserController::class, 'showFormUpdateProfile'])->name('profiles.showFormUpdateProfile');
            Route::post('/{id}/update-profile', [UserController::class, 'updateProfile'])->name('profiles.updateProfile');
        });
        //Route reset-password
        Route::post('/reset-password', [ResetPasswordController::class, 'resetPassword'])->name('reset-password');
        //Export data
        Route::get('/export', [UserController::class, 'export'])->name('export');
    });
    });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class User extends Authenticatable
{
    use HasFactory;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    protected $table = 'users';

    public function department()
    {
        return $this->belongsTo(Department::class, 'department_id', 'id');
    }

    public function role()
    {
        return $this->hasOne(Role::class, 'id', 'role_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Exports\UserExport;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Excel;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Http\Requests\UpdateProfileRequest;
use App\Repositories\Role\RoleRepositoryInterface;
use App\Repositories\User\UserRepositoryInterface;
use Intervention\Image\ImageManagerStatic as Image;
use App\Repositories\Department\DepartmentRepositoryInterface;

class UserController extends Controller
{
    public function __construct(UserRepositoryInterface $user, DepartmentRepositoryInterface $department, RoleRepositoryInterface $role)
    {
        $this->user = $user;
        $this->department = $department;
        $this->role = $role;
    }

    public function index(Request $request)
    {
        $data = $request->only('department_id', 'keyword');
        if (Auth::user()->is_admin) {
            $users = $this->user->getAllFilter($data);
            $departments = $this->department->getAll();
        } else {
            $data['department_id'] = Auth::user()->department_id;
            $data['role_id'] = config('const.ROLE_EMPLOYEE');
            $users = $this->user->getAllFilter($data);
            $departments = $this->department->getById(Auth::user()->department_id);
        }
        return view('users.list', compact('users', 'departments'));
    }

    public function create()
    {
        if (Gate::allows(config('const.ROLE.ADMIN'))) {
            $departments = $this->department->getAll();
            $roles = $this->role->getAll();
            return view('users.create', compact('departments', 'roles'));
        } else {
            abort(403);
        }
    }

    public function store(CreateUserRequest $request)
    {
        $data = $request->except('_token');
        $data['password'] = Hash::make($request->password);
        $checkManager = $this->user->findManager($data['department_id']);
        if (isset($checkManager) && $data['role_id'] == config('const.ROLE_MANAGER')) {
            return redirect()->back()->with('error', 'Phòng này đã có quản lí !');
        }
        // if ($request->hasFile('image')) {
        //     $image = $request->file('image');
        //     $filename = $image->getClientOriginalName();
        //     $image_resize = Image::make($image->getRealPath());
        //     $image_resize->resize(300, 300);
        //     $image_resize->save(public_path('images/' . $filename));
        //     $data['image'] = $filename;
        //     if (!empty($request->old_image)) {
        //         Storage::delete('images/' . $request->old_image);
        //     }
        // }
        $data['first_login'] = config('const.FIRSTLOGIN');
        $this->user->store($data);
        return redirect()->route('users.index')->with('success', 'Thêm mới thành công !');
    }

    public function edit($id)
    {
        if (Gate::allows(config('const.ROLE.ADMIN'))) {
            $departments = $this->department->getAll();
            $roles = $this->role->getAll();
            $user = $this->user->getById($id);
            return view('users.update', compact('user', 'departments', 'roles'));
        } else {
            abort(403);
        }
    }

    public function update(UpdateUserRequest $request, $id)
    {
        if (Auth::user()->id == $id && Auth::user()->role_id != $request->role_id) {
            return redirect()->route('users.edit', $id)->with('error', 'Không thể thay quyền của chính mình !');
        }
        $data = $request->except('_token');
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $filename = $image->getClientOriginalName();
            $image_resize = Image::make($image->getRealPath());
            $image_resize->resize(300, 300);
            $image_resize->save(public_path('images/' . $filename));
            $data['image'] = $filename;
            if (!empty($request->old_image)) {
                Storage::delete('images/' . $request->old_image);
            }
        }
        $checkManager = $this->user->findManager($data['department_id']);
        if (isset($checkManager) && $data['role_id'] == config('const.ROLE_MANAGER') && $checkManager->id != $id) {
            return redirect()->back()->with('error', 'Phòng này đã có quản lí !');
        }
        $this->user->update($data, $id);
        return redirect()->route('users.index')->with('success', 'Cập nhật thành công !');
    }

    public function destroy($id)
    {
        if (Gate::allows(config('const.ROLE.ADMIN'))) {
            if (Auth::user()->id == (int)$id) {
                return redirect()->route('users.index')->with('success', 'Xóa thành công!');
            } else {
                $this->user->destroy($id);
                return redirect()->route('users.index')->with('error', 'Xóa thất bại!');
            }
        } else {
            abort(403);
        }
    }

    public function showProfile()
    {
        $user = $this->user->getById(Auth::user()->id);
        return view('pages.profile', compact('user'));
    }

    public function showFormUpdateProfile($id)
    {
        if (Gate::allows(config('const.ROLE.ADMIN'))) {
            $user = $this->user->getById(Auth::user()->id);
            return view('pages.update-profile', compact('user'));
        } else {
            abort(403);
        }
    }

    public function updateProfile(UpdateProfileRequest $request, $id)
    {
        $data = $request->except('_token');
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $filename = $image->getClientOriginalName();
            $image_resize = Image::make($image->getRealPath());
            $image_resize->resize(300, 300);
            $image_resize->save(('images/' . $filename));
            $data['image'] = $filename;
            if (!empty($request->old_image)) {
                Storage::delete('images/' . $request->old_image);
            }
        }
        $this->user->update($data, $id);
        return redirect()->route('profile')->with('success', 'Cập nhật thành công !');
    }

    public function export(Excel $excel, Request $request)
    {
        $data = $request->all();
        $export = app()->makeWith(UserExport::class, compact('data'));
        $name =  uniqid() . '_user_information';
        return $excel->download($export, $name . '.xlsx');
    }
}

resources/views/users/create.blade.php
@extends('layouts.master')
@section('title', 'Thêm giảng viên')
@section('content')
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Thêm giảng viên</h4>
                @if (session()->has('error'))
                    <h6 class="alert alert-danger">
                        {{ session()->get('error') }}
                    </h6>
                @endif
                <form action="{{ route('users.store') }}" class="form-sample" method="post"
                    enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Họ tên <span class="text-danger">*</span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="name" class="form-control" value="{{old('name')}}"/>
                                    @error('name')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Email <span class="text-danger">*</span></label>
                                <div class="col-sm-9">
                                    <input type="email" name="email" class="form-control" value="{{old('email')}}" placeholder="username@gmail.com"/>
                                    @error('email')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Số điện thoại </label>
                                <div class="col-sm-9">
                                    <input type="text" name="phone" class="form-control" value="{{old('phone')}}"/>
                                    @error('phone')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Password <span class="text-danger">*</span></label>
                                <div class="col-sm-9">
                                    <input type="password" name="password" class="form-control" />
                                    @error('password')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Ngày sinh <span class="text-danger">*</span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="birthday" class="form-control" value="{{old('birthday')}}" placeholder="ex: y-m-d"/>
                                    @error('birthday')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label"> Khoa <span class="text-danger">*</span></label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="department_id">
                                        <option>--Chọn khoa--</option>
                                        @foreach ($departments as $department)
                                            <option value="{{ $department->id }}">{{ $department->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('department_id')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Role <span class="text-danger">*</span></label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="role_id">
                                        <option >--Select Role--</option>
                                        @foreach ($roles as $role)
                                            <option value="{{ $role->id }}">{{ $role->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('role_id')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Địa chỉ <span class="text-danger">*</span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="address" class="form-control" value="{{old('address')}}"/>
                                    @error('address')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn  btn-primary mr-2 ">Submit</button>
                    <button type="button" onclick="window.location.href='{{ route('users.index') }}'"
                        class="btn btn-light">Cancel
                    </button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/users/list.blade.php
@extends('layouts.master')
@section('title', 'Danh sach giảng viên')
@section('content')
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Danh sách giảng viên</h4>
                @if (session()->has('success'))
                    <h6 class="alert alert-success">
                        {{ session()->get('success') }}
                    </h6>
                @endif
                @if (session()->has('error'))
                    <h6 class="alert alert-danger">
                        {{ session()->get('error') }}
                    </h6>
                @endif

                    <ul class="mr-lg-2">
                        <li class="d-none d-lg-block">
                            <input type="text" id="exportData" value="{{ route('export') }}" hidden>
                            <form id="submit" action="" method="get">
                                <div class="d-flex flex-row">
                                    <div class="p-2 d-flex flex-row">
                                        <select name="department_id" class="form-control select2">
                                            <option value="" selected disabled>--Chọn khoa--</option>
                                            @foreach ($departments as $department)
                                                <option value="{{ $department-> id }}"
                                                    @if (isset($_GET['department_id']) && $_GET['department_id'] == $department->id) selected @endif>
                                                {{ $department->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    {{-- <div class="p-2 d-flex flex-row">
                                        <select name="sort_type" class="form-control select2">
                                            <option value="" selected disabled>--Select--</option>
                                            <option value="ASC"
                                            @if (isset($_GET['sort_type']) && $_GET['sort_type'] == 'ASC') selected @endif>
                                            Tăng dần</option>
                                            <option value="DESC"
                                            @if (isset($_GET['sort_type']) && $_GET['sort_type'] == 'DESC') selected @endif>
                                            Giảm dần</option>
                                        </select>
                                    </div> --}}

                                    <div class="ml-auto p-2 d-flex flex-row">
                                        <input class="form-control" id="navbar-search-input" name="keyword"
                                            placeholder="Search" aria-label="search" aria-describedby="search">
                                        <button type="button" class="btn btn-primary filterButton">
                                            <i class="ti-search text-white"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </li>
                    </ul>
                <table class="table table-striped" style="text-align:center">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Họ tên</th>
                            <th>Năm sinh</th>
                            <th>Địa chỉ</th>
                            <th>Số điện thoại</th>
                            <th>Email</th>
                            <th>Khoa giảng dạy</th>
                            <th>Role</th>
                            <th colspan="2">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $key => $user)
                            <tr>
                                <td>{{ $key + 1 }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->birthday }}</td>
                                <td>{{ $user->address }}</td>
                                <td>{{ $user->phone }}</td>
                                <td>{{ $user->email }}</td>
                                <!-- <td>{{ date('Y-m-d', strtotime($user->work_at)) }}</td>  -->
                                <td>{{ $user->department->name }}</td>
                                <td>{{ $user->role->name }}</td>
                                <!-- <td>
                                    @if (config('const.WORKSTATUS.Retired') == $user->work_status)
                                    <span class="badge badge-danger">{{ __('message.WORKSTATUS.' . $user->work_status) }}</span>
                                    @else
                                    <span class="badge badge-success">{{ __('message.WORKSTATUS.' . $user->work_status) }}</span>
                                    @endif
                                </td> -->
                                @can(config('const.ROLE.ADMIN'))
                                    <td>
                                        <a href="{{ route('users.edit', $user->id) }}" class="btn btn-primary">
                                            <i class="ti-marker-alt text-white" aria-hidden="true"></i>
                                        </a>
                                        <a class="btn btn-danger" href="#" data-toggle="modal"
                                            data-target="#modal-delete{{ $user->id }}">
                                            <i class="ti-trash text-white" aria-hidden="true"></i>
                                        </a>
                                        <a class="btn btn-danger" href="#" data-toggle="modal"
                                            data-target="#modal-reset{{ $user->id }}">
                                            <i class="ti-reload text-white" aria-hidden="true"></i>
                                        </a>
                                        <form id="delete_form_{{ $user->id }}" method="post"
                                            action="{{ route('users.destroy', $user->id) }}" style="display:none">
                                            @method('DELETE')
                                            @csrf
                                        </form>
                                    </td>
                                @endcan
                                @include('modals.delete-user')
                                @include('modals.reset-password')
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $users->appends(request()->all())->links() }}
            </div>
        </div>
    </div>
@endsection