routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\Auth\ResetPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});
//Route login-logout
Route::prefix('homes')->group(function () {
    Route::get('/login', [LoginController::class, 'showFormLogin'])->name('login');
    Route::post('/login', [LoginController::class, 'login'])->name('homes.login');
    Route::get('/logout', [LoginController::class, 'logout'])->name('homes.logout');
});
//Route middleware-auth
Route::middleware('auth')->group(function () {
    //Route change-password
    Route::get('/change-password', [LoginController::class, 'showFormChangePassword'])->name('homes.showFormChangePassword');
    Route::post('/change-password', [LoginController::class, 'changePassword'])->name('homes.changePassword');
    //Route profile-view
    Route::get('/profile', [UserController::class, 'showProfile'])->name('profile');
    //Route list-user
    Route::get('/users/list', [UserController::class, 'index'])->name('users.index')->middleware('check-permission:' . config('const.ROLE.MANAGER'));
    //Route check first-login && check-role
    Route::middleware('check-permission')->group(function () {
        //Route departments
        Route::resource('departments', 'DepartmentController')->except(['edit', 'update', 'destroy']);
        Route::get('{id}/edit', [DepartmentController::class, 'edit'])->name('departments.edit');
        Route::post('{id}/update', [DepartmentController::class, 'update'])->name('departments.update');
        Route::get('{id}/delete', [DepartmentController::class, 'destroy'])->name('departments.destroy');
        //Route classes
        Route::resource('classes', 'ClassesController')->except(['edit', 'update', 'destroy']);
        Route::get('{id}/edit', [ClassesController::class, 'edit'])->name('classes.edit');
        Route::post('{id}/update', [ClassesController::class, 'update'])->name('classes.update');
        Route::get('{id}/delete', [ClassesController::class, 'destroy'])->name('classes.destroy');
        //Route Schedule
        Route::resource('schedule', 'ScheduleController')->except(['edit', 'destroy']);
        Route::get('{id}/edit', [ScheduleController::class, 'edit'])->name('schedules.edit');
        Route::get('{id}/delete', [ScheduleController::class, 'destroy'])->name('schedules.destroy');

        //Route users
        Route::resource('users', 'UserController')->except(['index']);
        //Route profile
        Route::prefix('profiles')->group(function () {
            Route::get('/{id}/update-profile', [UserController::class, 'showFormUpdateProfile'])->name('profiles.showFormUpdateProfile');
            Route::post('/{id}/update-profile', [UserController::class, 'updateProfile'])->name('profiles.updateProfile');
        });
        //Route reset-password
        Route::post('/reset-password', [ResetPasswordController::class, 'resetPassword'])->name('reset-password');
        //Export data
        Route::get('/export', [UserController::class, 'export'])->name('export');
    });
    });

resources/views/layouts/footer.blade.php
<!-- <footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Design © 2021. Premium <a
                href="https://rikkeisoft.com/en/" target="_blank">Rikkei</a>
        </span>
    </div>
</footer> -->

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        @yield('title')
    </title>
    <base href="{{ asset('') }}template/">
    <!-- plugins:css -->
    @section('css')
        <link rel="stylesheet" href="vendors/feather/feather.css">
        <link rel="stylesheet" href="vendors/ti-icons/css/themify-icons.css">
        <link rel="stylesheet" href="vendors/css/vendor.bundle.base.css">
        <!-- endinject -->
        <!-- Plugin css for this page -->
        <link rel="stylesheet" href="vendors/datatables.net-bs4/dataTables.bootstrap4.css">
        <link rel="stylesheet" href="vendors/ti-icons/css/themify-icons.css">
        <link rel="stylesheet" type="text/css" href="js/select.dataTables.min.css">
        <link rel="stylesheet" href="../../vendors/select2/select2.min.css">
        <link rel="stylesheet" href="../../vendors/select2-bootstrap-theme/select2-bootstrap.min.css">
        <!-- End plugin css for this page -->
        <!-- inject:css -->
        <link rel="stylesheet" href="css/vertical-layout-light/style.css">
        <!-- endinject -->
        <link rel="shortcut icon" href="images/favicon.png" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
        <link rel="stylesheet" href="css/font-awesome.min.css">
        <link rel="stylesheet" href="css/custom.css">
    @show
</head>

<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->

        @include('layouts.navbar')

        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial -->
            <!-- partial:partials/_sidebar.html -->
            @include('layouts/sidebar')
            <!-- partial -->
            <div class="main-panel">
                @yield('content')
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                @include('layouts/footer')
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    @section('script')
        <script src="vendors/js/vendor.bundle.base.js"></script>
        <!-- endinject -->
        <!-- Plugin js for this page -->
        <script src="vendors/chart.js/Chart.min.js"></script>
        <script src="vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
        <script src="js/dataTables.select.min.js"></script>

        <!-- End plugin js for this page -->
        <!-- inject:js -->
        <script src="js/off-canvas.js"></script>
        <script src="js/hoverable-collapse.js"></script>
        <script src="js/template.js"></script>
        <script src="js/settings.js"></script>
        <script src="js/todolist.js"></script>
        <!-- endinject -->
        <!-- Custom js for this page-->
        <script src="js/dashboard.js"></script>
        <script src="js/Chart.roundedBarCharts.js"></script>
        <script src="../../js/file-upload.js"></script>
        <script src="../../js/typeahead.js"></script>
        <script src="../../js/select2.js"></script>
        <script src="../../vendors/typeahead.js/typeahead.bundle.min.js"></script>
        <script src="../../vendors/select2/select2.min.js"></script>
        <!-- End custom js for this page-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous">
        </script>
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script src="js/export.js"></script>
    @show
</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo mr-5" href="{{ route('users.index') }}">
            {{-- <img src="images/logo.svg" class="mr-2" alt="logo" /> --}}
        </a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="icon-menu">
            </span>
        </button>
        @can(config('const.ROLE.ADMIN'))
        <div class="mr-auto p-3 d-flex">
            <button type="button" class="btn btn-primary exportButton">
                <i class="ti-printer text-white"></i>
            </button>
        </div>
        @endcan
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <span>Hello <b>{{ Auth::user()->name }}
                        @if (Auth::user()->is_admin)
                            (Admin)
                        @endif
                    </b></span>
            </li>
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                    @if (isset(Auth::user()->image))
                        <img src="{{ asset('images/' . Auth::user()->image) }}" alt="profile" />
                    @else
                        <img src="{{ asset('uploads/' . 'avatar.png') }}" alt="">
                    @endif
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                    <a href="{{ route('profile') }}" class="dropdown-item">
                        <i class="ti-eye text-primary"></i>
                        Profile
                    </a>
                    <a href="{{ route('homes.showFormChangePassword') }}" class="dropdown-item">
                        <i class="ti-key text-primary"></i>
                        Change Password
                    </a>
                    <a href="{{ route('homes.logout') }}" class="dropdown-item">
                        <i class="ti-power-off text-primary"></i>
                        Logout
                    </a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
            data-toggle="offcanvas">
            <span class="icon-menu"></span>
        </button>
    </div>
</nav>

resources/views/layouts/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    @can(config('const.ROLE.ADMIN'))
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#form-elements" aria-expanded="false"
                    aria-controls="form-elements">
                    <i class="icon-columns menu-icon"></i>
                    <span class="menu-title">Giảng viên</span>

                </a>
                <div class="collapse" id="form-elements">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item"><a class="nav-link" href="{{ route('users.index') }}">Danh sách </a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('users.create') }}">Thêm giảng viên</a></li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false"
                    aria-controls="ui-basic">
                    <i class="icon-layout menu-icon"></i>
                    <span class="menu-title">Khoa</span>

                </a>
                <div class="collapse" id="ui-basic">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item"> <a class="nav-link" href="{{ route('departments.index') }}">Danh sách khoa</a></li>
                        <li class="nav-item"> <a class="nav-link" href="{{route('departments.create')}}">Thêm khoa</a></li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#ui" aria-expanded="false"
                    aria-controls="ui">
                    <i class="icon-layout menu-icon"></i>
                    <span class="menu-title">Lớp</span>

                </a>
                <div class="collapse" id="ui">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item"> <a class="nav-link" href="{{route('classes.index') }}">Danh sách lớp</a></li>
                        <li class="nav-item"> <a class="nav-link" href="{{route('classes.create')}}">Thêm lớp</a></li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#ui-2" aria-expanded="false"
                    aria-controls="ui-2">
                    <i class="icon-layout menu-icon"></i>
                    <span class="menu-title">Quản lý giảng dạy</span>

                </a>
                <div class="collapse" id="ui-2">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item"> <a class="nav-link" href="{{route('schedule.index') }}">Thời khóa biểu</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    @endcan
</nav>