routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\Auth\ResetPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});
//Route login-logout
Route::prefix('homes')->group(function () {
    Route::get('/login', [LoginController::class, 'showFormLogin'])->name('login');
    Route::post('/login', [LoginController::class, 'login'])->name('homes.login');
    Route::get('/logout', [LoginController::class, 'logout'])->name('homes.logout');
});
//Route middleware-auth
Route::middleware('auth')->group(function () {
    //Route change-password
    Route::get('/change-password', [LoginController::class, 'showFormChangePassword'])->name('homes.showFormChangePassword');
    Route::post('/change-password', [LoginController::class, 'changePassword'])->name('homes.changePassword');
    //Route profile-view
    Route::get('/profile', [UserController::class, 'showProfile'])->name('profile');
    //Route list-user
    Route::get('/users/list', [UserController::class, 'index'])->name('users.index')->middleware('check-permission:' . config('const.ROLE.MANAGER'));
    //Route check first-login && check-role
    Route::middleware('check-permission')->group(function () {
        //Route departments
        Route::resource('departments', 'DepartmentController')->except(['edit', 'update', 'destroy']);
        Route::get('{id}/edit', [DepartmentController::class, 'edit'])->name('departments.edit');
        Route::post('{id}/update', [DepartmentController::class, 'update'])->name('departments.update');
        Route::get('{id}/delete', [DepartmentController::class, 'destroy'])->name('departments.destroy');
        //Route classes
        Route::resource('classes', 'ClassesController')->except(['edit', 'update', 'destroy']);
        Route::get('{id}/edit', [ClassesController::class, 'edit'])->name('classes.edit');
        Route::post('{id}/update', [ClassesController::class, 'update'])->name('classes.update');
        Route::get('{id}/delete', [ClassesController::class, 'destroy'])->name('classes.destroy');
        //Route Schedule
        Route::resource('schedule', 'ScheduleController')->except(['edit', 'destroy']);
        Route::get('{id}/edit', [ScheduleController::class, 'edit'])->name('schedules.edit');
        Route::get('{id}/delete', [ScheduleController::class, 'destroy'])->name('schedules.destroy');

        //Route users
        Route::resource('users', 'UserController')->except(['index']);
        //Route profile
        Route::prefix('profiles')->group(function () {
            Route::get('/{id}/update-profile', [UserController::class, 'showFormUpdateProfile'])->name('profiles.showFormUpdateProfile');
            Route::post('/{id}/update-profile', [UserController::class, 'updateProfile'])->name('profiles.updateProfile');
        });
        //Route reset-password
        Route::post('/reset-password', [ResetPasswordController::class, 'resetPassword'])->name('reset-password');
        //Export data
        Route::get('/export', [UserController::class, 'export'])->name('export');
    });
    });

app/Http/Controllers/ClassesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Maatwebsite\Excel\Excel;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\ClassesRequest;
use App\Repositories\User\UserRepositoryInterface;
use App\Repositories\Classes\ClassesRepositoryInterface;

class ClassesController extends Controller
{
    function __construct(ClassesRepositoryInterface $classes, UserRepositoryInterface $users)
    {
        $this->classes = $classes;
    }

    public function index()
    {
        $classes = $this->classes->getAllClasses();
        return view('classes.list', compact("classes"));
    }

    public function create()
    {
        return view('classes.create');
    }

    public function store(ClassesRequest $request)
    {
        $data = $request->except('_token');
        $this->classes->store($data);
        return redirect()->route('classes.index')->with('success', 'Tạo lớp thành công!');
    }

    public function edit($id)
    {
        $classes = $this->classes->getById($id);
        return view('classes.update', compact('classes'));
    }

    public function update(ClassesRequest $request, $id)
    {
        $data = $request->except("_token");
        $this->classes->update($data, $id);
        return redirect()->route('classes.index')->with('success', 'Sửa khoa thành công!');
    }

    public function destroy($id)
    {
        $this->classes->destroy($id);
        return redirect()->route('classes.index')->with('success', 'Xoá khoa thành công!');
    }
}

resources/views/Classes/create.blade.php
@extends('layouts.master')
@section('title')
    Thêm
@endsection
@section('content')
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Thêm Lớp</h4>
                <form action="{{ route('classes.store') }}" class="forms-sample" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="exampleInputClassesname">Tên <span class="text-danger">*</span></label>
                        <input type="text" name="name" class="form-control" >
                        @error('name')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputManager">Chủ nhiệm <span class="text-danger" >*</span></label>
                        <input type="text" name='manager' class='form-control'>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button type="button" onclick="window.location.href='{{ route('classes.index') }}'"
                        class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/Classes/list.blade.php
@extends('layouts.master')
@section('title')
    Dánh sách lớp
@endsection
@section('content')
    <div class="col-lg-12 grid-margin stretch-card background-color-grey">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Dánh sách lớp</h4>
                <p class="card-description">
                </p>
                @if (session()->has('success'))
                    <h3 class="alert alert-success">
                        {{ session()->get('success') }}
                    </h3>
                @endif
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Tên lớp</th>
                            <th>Chủ nhiệm</th>
                            <th>Create at</th>
                            <th>Update at</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (count($classes))
                            @foreach ($classes as $key => $classes)
                                <tr>
                                    <td class="py-1">
                                        {{ $key + 1 }}
                                    </td>
                                    <td>
                                        {{ $classes->name }}
                                    </td>
                                    <td>
                                        {{ $classes->manager }}
                                    </td>
                                    {{-- <td>
                                        <!-- @foreach ($department->user as $manager)
                                            {{ $manager->name . '. ' }}
                                        @endforeach -->
                                    </td> --}}
                                    <td>
                                        {{ $classes->created_at->format("d/m/Y") }}
                                    </td>
                                    <td>
                                        {{ $classes->updated_at->format("d/m/Y") }}
                                    </td>
                                    <td>
                                        <a href="{{ route('classes.edit', $classes->id) }}"
                                            class="btn btn-primary mr-2">
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        </a>
                                        <a class="btn btn-danger" href="#" data-toggle="modal"
                                            data-target="#ModalDelete{{ $classes->id }}">
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                        </a>
                                        <form id="delete_form_{{ $classes->id }}" method="get"
                                            action="{{ route('classes.destroy', $classes->id) }}"
                                            style="display:none">
                                            @csrf
                                        </form>
                                    </td>
                                    @include('modals.delete-classes')
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td class="text-center" colspan="12">Không tìm thấy trang</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
                {{-- {{ $classes->links() }} --}}
            </div>
        </div>
    </div>
@endsection

resources/views/Classes/update.blade.php
@extends('layouts.master')
@section('title')
    Danh sách Lớp
@endsection
@section('content')
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Cập nhập</h4>
                <form action="{{route('classes.update', $classes->id) }}" class="forms-sample" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="exampleInputClassesname">Tên khoa <span class="text-danger">*</span></label>
                        <input type="text" name="name" class="form-control" value="{{ $classes->name }}">
                        @error('name')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputManager">Chủ nhiệm <span class="text-danger">*</label>
                        <input type="text" name="manager" class="form-control" value="{{ $classes->manager }}">
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button type="button" onclick="window.location.href='{{ route('classes.index') }}'"
                        class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
@endsection